services:
  keycloak:
    container_name: "keycloak-container"
    image: quay.io/keycloak/keycloak:25.0
    command: [ "start-dev", "--http-relative-path=keycloak/auth" ]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8080/keycloak/auth/"
      KC_PROXY: "edge"
      KC_DB: "postgres"
      KC_DB_PASSWORD: "${DB_PASSWORD}"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/library_db" # Call the postgres service
      KC_DB_USERNAME: "postgres"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres-container"
    image: "postgres:latest"
    platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "library_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  students-app:
    container_name: "lib-container"
    build:
      context: .
      dockerfile: Dockerfile
    image: "muhohoweb/library-image:1.0.0"
    platform: linux/amd64
    restart: always
    ports:
      - "8082:8082"
    environment:
      STUDENTS_URL: "${STUDENTS_URL}"
      KEY_CLOAK_DB_URL: "${KEY_CLOAK_DB_URL}"
      KEY_CLOAK_CLIENT_ID: "${KEY_CLOAK_CLIENT_ID}"
      KEY_CLOAK_USERNAME: "${KEY_CLOAK_USERNAME}"
      KEY_CLOAK_PASSWORD: "${KEY_CLOAK_PASSWORD}"


      DB_USER: "${DB_USER}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_URL: "jdbc:postgresql://postgres:5432/library_db"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  cache:
  postgres-data:
  kafka-data:
#
