spring:
  profiles:
    active: "prod"
  application:
    name: library

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY_CLOAK_ISSUER_URI}
          jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/protocol/openid-connect/certs
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: library


server:
  port: 8080

students:
  url: ${STUDENTS_URL}

jasypt:
  encryptor:
    password: hG7@eT!3rK9$yW0&  # The same secret key as in JasyptConfig
    algorithm: PBEWithMD5AndDES

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  sqs:
    queueUrl: https://sqs.us-east-1.amazonaws.com/975049979529/sqs_queue

